spring:
  application:
    name: clinic
  datasource:
    url: jdbc:h2:mem:clinicdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
#  datasource:
#    url: jdbc:postgresql://localhost:5432/clinicdb
#    username: postgres
#    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8778
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true

logging:
  level:
    com.clinic: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG